// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCkxmWygh-ybEmYO9vOhBzlaOaf4VUV4g',
    appId: '1:723232938358:web:243e8394dc851d2e0c4257',
    messagingSenderId: '723232938358',
    projectId: 'scarecrow-e4060',
    authDomain: 'scarecrow-e4060.firebaseapp.com',
    storageBucket: 'scarecrow-e4060.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB-AgH9UBrWC9hwa9Fik4mgV_qZ_i0aWs',
    appId: '1:723232938358:ios:91fa39af028f2e460c4257',
    messagingSenderId: '723232938358',
    projectId: 'scarecrow-e4060',
    storageBucket: 'scarecrow-e4060.firebasestorage.app',
    iosBundleId: 'com.example.seniorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCkxmWygh-ybEmYO9vOhBzlaOaf4VUV4g',
    appId: '1:723232938358:web:49b48a97a915f45a0c4257',
    messagingSenderId: '723232938358',
    projectId: 'scarecrow-e4060',
    authDomain: 'scarecrow-e4060.firebaseapp.com',
    storageBucket: 'scarecrow-e4060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB-AgH9UBrWC9hwa9Fik4mgV_qZ_i0aWs',
    appId: '1:723232938358:ios:91fa39af028f2e460c4257',
    messagingSenderId: '723232938358',
    projectId: 'scarecrow-e4060',
    storageBucket: 'scarecrow-e4060.firebasestorage.app',
    iosBundleId: 'com.example.seniorApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfIdArfD9VJe-Sl5W9tXM4qQyMUXYsOHc',
    appId: '1:723232938358:android:fe8b8954cebb70cd0c4257',
    messagingSenderId: '723232938358',
    projectId: 'scarecrow-e4060',
    storageBucket: 'scarecrow-e4060.firebasestorage.app',
  );

}